# server.port=8090
# TEST=${NAME}
# USER=Janakar
# Spring Properties
DB_MANAGER_SERVICE:
  db-manager
spring:
  application:
     name: consumer-service
  cloud:
    inetutils:
      ignoredInterfaces:
        - db-*

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port