name: Deployment
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
#       - name: list
#         working-directory: ./initial
#         run: ls
      - name: deploy
        working-directory: ./initial
        run: ../../initial/gradlew war
