name: Deployment
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: change working directory
        run: cd ..\..\initial
      - name: list files
        run: ls
#       - name: deploy
#         run: ../../initial/gradlew war
